server:
  port: 8083

logging:
  level:
    root: INFO

spring:
  application:
    name: notificator
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_URL:http://localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true