server:
  port: 8080

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: order-writer
          uri: lb://order-writer
          predicates:
            - Path=/order/**
            - Method=POST
          filters:
            - RewritePath=/order, /v1/order
        - id: notificator
          uri: lb://notificator
          predicates:
            - Path=/notify/**
            - Method=POST
          filters:
            - RewritePath=/notify/(?<segment>.*), /v1/notify/${segment}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_URL:http://localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true