services:

  api-gateway:
    container_name: api-gateway
    build: ../gateway
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-prod}
      - EUREKA_CLIENT_URL=${EUREKA_CLIENT_URL:-http://eureka-server:8761/eureka/}
    networks:
      - order-system-net

  order-writer:
    container_name: order-writer
    build: ../order-writer
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-prod}
      - KAFKA_BOOTSTRAP_SERVERS=${KAFKA_SERVER:-kafka:9092}
      - KAFKA_SERVER=${KAFKA_SERVER:-kafka:9092}
      - KAFKA_TOPIC=${KAFKA_TOPIC:-orders}
      - EUREKA_CLIENT_URL=${EUREKA_CLIENT_URL:-http://eureka-server:8761/eureka/}
    networks:
      - order-system-net

  order-processor:
    container_name: order-processor
    build: ../order-processor
    ports:
      - "8082:8080"
    depends_on:
      - kafka
      - ravendb
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-prod}
      - KAFKA_BOOTSTRAP_SERVERS=${KAFKA_SERVER:-kafka:9092}
      - KAFKA_ORDERS_TOPIC=${KAFKA_ORDERS_TOPIC:-orders}
      - KAFKA_GROUP_ID=${KAFKA_GROUP_ID:-order-processor}
      - RAVENDB_URL=${RAVENDB_URL:-http://ravendb:8080}
      - RAVENDB_DATABASE=${RAVENDB_DATABASE:-orders}
      - NOTIFICATOR_URL=${NOTIFICATOR_URL:-http://notificator:8083}
    networks:
      - order-system-net

  notificator:
    container_name: notificator
    build: ../notificator
    ports:
      - "8083:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-prod}
      - MAIL_HOST=${MAIL_HOST:-smtp.gmail.com}
      - MAIL_PORT=${MAIL_PORT:-587}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - EUREKA_CLIENT_URL=${EUREKA_CLIENT_URL:-http://eureka-server:8761/eureka/}
    networks:
      - order-system-net

  eureka-server:
    container_name: eureka-server
    build: ../eureka
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-prod}
    networks:
      - order-system-net

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_KRAFT_CLUSTER_ID=abcdefghijklmnopqrstuv
    volumes:
      - kafka-data:/bitnami/kafka
    networks:
      - order-system-net

  ravendb:
    image: ravendb/ravendb:6.0-latest
    container_name: ravendb
    ports:
      - "8089:8080"
    environment:
      - RAVEN_Setup_Mode=None
      - RAVEN_Security_UnsecuredAccessAllowed=PublicNetwork
    volumes:
      - ravendb-data:/opt/RavenDB/Server/RavenData
    networks:
      - order-system-net

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - order-system-net
    volumes:
      - redis-data:/data

volumes:
  kafka-data:
  ravendb-data:
  redis-data:

networks:
  order-system-net:
    driver: bridge