server:
    port: 8081

logging:
  level:
    root: INFO

kafka:
  server: ${KAFKA_SERVER:http://localhost:9092}
  topic: ${KAFKA_TOPIC:orders}

spring:
  application:
    name: order-writer
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:http://localhost:9092}

springdoc:
  swagger-ui:
    path: /swagger

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_URL:http://localhost:8761/eureka/}