server:
  port: 8082

logging:
  level:
    root: INFO

kafka:
  topic: ${KAFKA_ORDERS_TOPIC:orders}
  groupId: ${KAFKA_GROUP_ID:order-processor}

ravendb:
  url: ${RAVENDB_URL:http://localhost:8089}
  database: ${RAVENDB_DATABASE:orders}

notificator-url: ${NOTIFICATOR_URL:http://localhost:8083}

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:http://localhost:9092}
    listener:
      ack-mode: manual
    consumer:
      group-id: order-processor
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.json.trusted.packages: "*"