name: "[CI] Notificator Service"

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - 'notificator/**'
      - '.github/workflows/notificator-ci.yaml'

jobs:
  test-notificator:
    name: Test Notificator Service
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./notificator
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Test with Gradle
        run: ./gradlew test